const animes = [
  { name: "OnePiece", slug: "one-piece" },
  { name: "DragonBall", slug: "dragon-ball" },
  { name: "DragonBallZ", slug: "dragon-ball-z" },
  { name: "DragonBallSuper", slug: "dragon-ball-super" },
  { name: "MyHeroAcademia", slug: "my-hero-academia" },
  { name: "VinlandSaga", slug: "vinland-saga" },
  { name: "SoloLeveling", slug: "solo-leveling" },
  { name: "KurokoBasket", slug: "kurokos-basketball" },
  { name: "JujutsuKaisen", slug: "jujutsu-kaisen" },
  { name: "BlackClover", slug: "black-clover" },
  { name: "HunterXHunter", slug: "hunter-x-hunter" },
  { name: "Mashle", slug: "mashle-magic-and-muscles" },
  { name: "AttaqueDesTitans", slug: "lattaque-des-titans" },
  { name: "DeathNote", slug: "death-note" },
  { name: "TheGodOfHighschool", slug: "the-god-of-high-school" },
  { name: "TowerOfGod", slug: "tower-of-god" },
  { name: "Naruto", slug: "naruto" },
  { name: "NarutoShippuden", slug: "naruto-shippuden" },
  { name: "ShangriLaFrontier", slug: "shangri-la-frontier" },
  { name: "ClassroomOfTheElites", slug: "classroom-of-the-elite" },
  {
    name: "TheDailyLifeOfTheImmortalKing",
    slug: "the-daily-life-of-the-immortal-king",
  },
  { name: "Haikyuu", slug: "haikyu" },
  { name: "BlueLock", slug: "blue-lock" },
  { name: "AirGear", slug: "air-gear" },
  { name: "SlamDunk", slug: "slam-dunk" },
  { name: "DemonSlayer", slug: "demon-slayer-kimetsu-no-yaiba" },
  { name: "Bleach", slug: "bleach" },
  { name: "Boruto", slug: "boruto-naruto-next-generations" },
  { name: "SwordArtOnline", slug: "sword-art-online" },
  { name: "OnePunchMan", slug: "one-punch-man" },
  { name: "TokyoGhoul", slug: "tokyo-ghoul" },
  { name: "ChainsawMan", slug: "chainsaw-man" },
  { name: "HellsParadise", slug: "hells-paradise" },
  { name: "FairyTail", slug: "fairy-tail" },
  { name: "EminenceInShadow", slug: "the-eminence-in-shadow" },
  { name: "MobPsycho100", slug: "mob-psycho-100" },
  { name: "HajimeNoIppo", slug: "hajime-no-ippo" },
  { name: "TokyoRevengers", slug: "tokyo-revengers" },
  { name: "BlueExorcist", slug: "blue-exorcist" },
  { name: "KaguraBachi", slug: "kagura-bachi" },
  { name: "CaptainTsubasa", slug: "captain-tsubasa" },
  { name: "Monster103", slug: "monster-103-mercies-dragon-damnation" },
  { name: "Monster", slug: "monster" },
  { name: "FireForce", slug: "fire-force" },
  { name: "AssassinationClassroom", slug: "assassination-classroom" },
  { name: "AoAshi", slug: "ao-ashi" },
  { name: "GurrenLagann", slug: "gurren-lagann" },
  { name: "SevenDeadlySins", slug: "seven-deadly-sins" },
  { name: "RagnaCrimson", slug: "ragna-crimson" },
  { name: "NinjaKamui", slug: "ninja-kamui" },
  { name: "YuyuHakusho", slug: "yuyu-hakusho" },
  { name: "Frieren", slug: "frieren" },
  { name: "Vagabond", slug: "vagabond" },
  { name: "TheBoxer", slug: "the-boxer" },
  { name: "DoomBreaker", slug: "doom-breaker" },
  { name: "Bucchigiri", slug: "bucchigiri" },
  { name: "FMAB", slug: "fullmetal-alchemist-brotherhood" },
  { name: "FMA", slug: "fullmetal-alchemist" },
  { name: "Baki", slug: "baki" },
  { name: "DragonBallGT", slug: "dragon-ball-gt" },
  { name: "EightySix", slug: "86-eighty-six" },
  { name: "SpyXFamily", slug: "spy-x-family" },
  { name: "CyberpunkEdgerunners", slug: "cyberpunk-edgerunners" },
  { name: "OshinoKo", slug: "oshi-no-ko" },
  { name: "MushokuTensei", slug: "mushoku-tensei-jobless-reincarnation" },
  { name: "GTO", slug: "great-teacher-onizuka" },
  { name: "SevenSeeds", slug: "7-seeds" },
  { name: "AkameGaKill", slug: "akame-ga-kill" },
  { name: "Erased", slug: "erased" },
  { name: "YourName", slug: "your-name" },
  { name: "Gintama", slug: "gintama" },
  { name: "SteinsGate", slug: "steins-gate" },
  { name: "CodeGeass", slug: "code-geass" },
  { name: "ReZero", slug: "re-zero-starting-life-in-another-world" },
  { name: "DragonQuest", slug: "dragon-quest" },
  { name: "JojoBizarreAdventure", slug: "jojos-bizarre-adventure" },
  { name: "WindBreaker", slug: "wind-breaker" },
  { name: "ReMonster", slug: "re-monster" },
  { name: "TheFable", slug: "the-fable" },
  { name: "NoGameNoLife", slug: "no-game-no-life" },
  { name: "ASilentVoice", slug: "a-silent-voice" },
  { name: "YourLieInApril", slug: "your-lie-in-april" },
  { name: "Toradora", slug: "toradora" },
  { name: "Noragami", slug: "noragami" },
  { name: "AngelBeats", slug: "angel-beats" },
  { name: "MiraiNikki", slug: "mirai-nikki" },
  { name: "ThePromisedNeverland", slug: "the-promised-neverland" },
  { name: "Evangelion", slug: "neon-genesis-evangelion" },
  { name: "CowboyBebop", slug: "cowboy-bebop" },
  { name: "KaguyaSama", slug: "kaguya-sama-love-is-war" },
  { name: "FruitsBasket", slug: "fruits-basket" },
  { name: "Clannad", slug: "clannad" },
  { name: "LesCarnetsDeLapothicaire", slug: "les-carnets-de-lapothicaire" },
  { name: "MarchComesinLikeaLion", slug: "march-comes-in-like-a-lion" },
  { name: "TheDangersInMyHeart", slug: "the-dangers-in-my-heart" },
  { name: "KaijuN8", slug: "kaiju-no-8" },
  { name: "VioletEvergarden", slug: "violet-evergarden" },
  { name: "Kingdom", slug: "kingdom" },
  { name: "Parasite", slug: "parasite" },
  { name: "SuperDragonBallHeroes", slug: "super-dragon-ball-heroes" },
  {
    name: "Yatagarasu",
    slug: "yatagarasu-the-raven-does-not-choose-its-master",
  },
  { name: "DrStone", slug: "dr-stone" },
  { name: "MadeInAbyss", slug: "made-in-abyss" },
  { name: "Rainbow", slug: "rainbow" },
  { name: "ViralHit", slug: "viral-hit" },
  { name: "SaintSeiya", slug: "saint-seiya" },
  { name: "BlackLagoon", slug: "black-lagoon" },
  { name: "BlackButler", slug: "black-butler" },
  { name: "FoodWars", slug: "food-wars" },
  { name: "SuicideSquadIsekai", slug: "suicide-squad-isekai" },
  { name: "Berserk", slug: "berserk" },
  { name: "GrandBlue", slug: "grand-blue" },
  { name: "PrisonSchool", slug: "prison-school" },
  { name: "Gleipnir", slug: "gleipnir" },
  { name: "DevilmanCrybaby", slug: "devilman-crybaby" },
  { name: "d91Days", slug: "91-days" },
  { name: "Vivy", slug: "vivy-fluorite-eyes-song" },
  { name: "JapanSinks", slug: "japan-sinks-2020" },
  { name: "RankingOfKings", slug: "ranking-of-kings" },
  { name: "Barakamon", slug: "barakamon" },
  { name: "DeathParade", slug: "death-parade" },
  { name: "RakudaiKishi", slug: "rakudai-kishi-no-cavalry" },
  { name: "TenseiShitara", slug: "moi-quand-je-me-reincarne-en-slime" },
  { name: "DetectiveConan", slug: "detective-conan" },
  { name: "DanDaDan", slug: "dan-da-dan" },
  { name: "DragonBallDaima", slug: "dragon-ball-daima" },
  { name: "SailorMoon", slug: "sailor-moon" },
  { name: "KenLeSurvivant", slug: "ken-le-survivant" },
  { name: "Arifureta", slug: "arifureta-from-commonplace-to-worlds-strongest" },
  { name: "SpareMeGreatLord", slug: "spare-me-great-lord" },
  { name: "Eyeshield21", slug: "eyeshield-21" },
  { name: "PianoForest", slug: "piano-forest" },
  { name: "AllOut", slug: "all-out" },
  {
    name: "FourKnightsOfTheApocalypse",
    slug: "four-knights-of-the-apocalypse",
  },
  { name: "Kaiji", slug: "kaiji" },
  { name: "Roshidere", slug: "roshidere" },
  { name: "TerraFormas", slug: "terra-formars" },
  { name: "SamuraiChamploo", slug: "samurai-champloo" },
  { name: "AfroSamurai", slug: "afro-samurai" },
  { name: "WhiteAlbum2", slug: "white-album-2" },
  { name: "Avatar", slug: "avatar-le-dernier-maitre-de-lair" },
  { name: "TheRisingOfTheShieldHero", slug: "the-rising-of-the-shield-hero" },
  { name: "DateALive", slug: "date-a-live" },
  { name: "Bakuman", slug: "bakuman" },
  { name: "MyHappyMariage", slug: "my-happy-mariage" },
  { name: "SeraphOfTheEnd", slug: "seraph-of-the-end" },
  { name: "FarmingLifeInAnotherWorld", slug: "farming-life-in-another-world" },
  { name: "Suzume", slug: "suzume" },
  { name: "DanMachi", slug: "danmachi-la-legende-des-familias" },
  { name: "Charlotte", slug: "charlotte" },
  { name: "Konosuba", slug: "konosuba-gods-blessing-on-this-wonderful-world" },
  { name: "BungouStrayDogs", slug: "bungou-stray-dogs" },
  { name: "VanitasNoCarte", slug: "vanitas-no-carte" },
  { name: "Castlevania", slug: "castlevania" },
  { name: "Gate", slug: "gate-au-dela-de-la-porte" },
  { name: "TimeShadows", slug: "time-shadows" },
  { name: "RisingImpact", slug: "rising-impact" },
  { name: "KenganAshura", slug: "kengan-ashura" },
  { name: "ValkyrieApocalypse", slug: "valkyrie-apocalypse" },
  { name: "NickyLarson", slug: "nicky-larson" },
  { name: "NarutoSDRockLee", slug: "naruto-sd-rock-lee" },
  { name: "Mushishi", slug: "mushishi" },
  { name: "BluePeriod", slug: "blue-period" },
  { name: "SaikiKusuo", slug: "saiki-kusuo-no-nan" },
  { name: "BuddyDaddies", slug: "buddy-daddies" },
  { name: "InitialD", slug: "initial-d" },
  { name: "VersatileMage", slug: "versatile-mage" },
  { name: "MobileSuitGundam", slug: "mobile-suit-gundam" },
  { name: "LonerLifeInAnotherWorld", slug: "loner-life-in-another-world" },
  { name: "Orient", slug: "orient" },
  { name: "InazumaEleven", slug: "inazuma-eleven" },
  { name: "Oregairu", slug: "oregairu" },
  { name: "Another", slug: "another" },
  { name: "EdensZero", slug: "edens-zero" },
  { name: "TheElusiveSamurai", slug: "the-elusive-samurai" },
  { name: "Sawako", slug: "sawako" },
  { name: "Magi", slug: "magi-the-labyrinth-of-magic" },
  { name: "VampireKnight", slug: "vampire-knight" },
  { name: "Beelzebub", slug: "beelzebub" },
  { name: "Wistoria", slug: "wistoria-wand-and-sword" },
  { name: "BlueBox", slug: "blue-box" },
  { name: "Hyouka", slug: "hyouka" },
  { name: "Akira", slug: "akira" },
  { name: "LeTombeauDesLucioles", slug: "le-tombeau-des-lucioles" },
  { name: "PrincesseMononoke", slug: "princesse-mononoke" },
  { name: "LeVoyageDeChihiro", slug: "le-voyage-de-chihiro" },
  { name: "PonyoSurLaFalaise", slug: "ponyo-sur-la-falaise" },
  { name: "LeChateauAmbulant", slug: "le-chateau-ambulant" },
  {
    name: "ShinmaiOssanBokensha",
    slug: "the-ossan-newbie-adventurer-trained-to-death-by-the-most-powerful-party-became-invincible",
  },
  { name: "TheBoondocks", slug: "the-boondocks" },
  { name: "SnowWhiteWithTheRedHair", slug: "shirayuki-aux-cheveux-rouges" },
  { name: "MyDressUpDarling", slug: "my-dress-up-darling" },
  { name: "JuujikaNoRokunin", slug: "juujika-no-rokunin" },
  { name: "SakamotoDays", slug: "sakamoto-days" },
  { name: "NobleNewWorldAdventures", slug: "noble-new-world-adventures" },
  { name: "BloomIntoYou", slug: "bloom-into-you" },
  { name: "Oresuki", slug: "oresuki" },
  { name: "BocchiTheRock", slug: "bocchi-the-rock" },
  { name: "EtrangerDeLaPlage", slug: "letranger-de-la-plage" },
  {
    name: "FailureFrame",
    slug: "failure-frame-i-became-the-strongest-and-annihilated-everything-with-low-level-spells",
  },
  { name: "Bofuri", slug: "bofuri" },
  { name: "Ranma", slug: "ranma-1-2" },
  { name: "RavenOfTheInnerPalace", slug: "raven-of-the-inner-palace" },
  { name: "PMLDA", slug: "more-than-a-married-couple-but-not-lovers" },
  { name: "Fate", slug: "fate" },
  { name: "Kenshin", slug: "kenshin-le-vagabond" },
  { name: "ACoupleOfCuckoos", slug: "a-couple-of-cuckoos" },
  {
    name: "TheMisfitOfDemonKingAcademy",
    slug: "the-misfit-of-demon-king-academy",
  },
  { name: "Reborn", slug: "reborn" },
  {
    name: "IllBecomeAVillainessThatWillGoDownInHistory",
    slug: "ill-become-a-villainess-who-goes-down-in-history",
  },
  { name: "NieRAutomata", slug: "nier-automata" },
  { name: "KimisamaKiss", slug: "kamisama-kiss" },
  { name: "SeireiGensouki", slug: "seirei-gensouki-spirit-chronicles" },
  { name: "Invaded", slug: "id-invaded" },
  { name: "Anohana", slug: "anohana" },
  { name: "MaidSama", slug: "kaichou-wa-maid-sama" },
  { name: "Given", slug: "given" },
  { name: "BlueSpringRide", slug: "blue-spring-ride" },
  { name: "TomodachiGame", slug: "tomodachi-game" },
  { name: "YuGiOh", slug: "yu-gi-oh" },
  { name: "UndeadUnluck", slug: "undead-unluck" },
  {
    name: "RascalDoesNotDreamOfBunnyGirlSenpai",
    slug: "rascal-does-not-dream-of-bunny-girl-senpai",
  },
  { name: "SoulEater", slug: "soul-eater" },
  { name: "ElfenLied", slug: "elfen-lied" },
  { name: "HellsingUltimate", slug: "hellsing-ultimate" },
  { name: "LoveChunibyoOtherDelusions", slug: "love-chunibyo-other-delusions" },
  { name: "SpiceAndWolf", slug: "spice-and-wolf" },
  { name: "GhostInTheShell", slug: "ghost-in-the-shell" },
  { name: "Durarara", slug: "durarara" },
  { name: "Baccano", slug: "baccano" },
  { name: "BakaAndTest", slug: "baka-to-test-to-shoukanjuu" },
  { name: "Monogatari", slug: "monogatari" },
  { name: "Btooom", slug: "btooom" },
  { name: "BloodLad", slug: "blood-lad" },
  { name: "BlackRockShooter", slug: "black-rock-shooter" },
  { name: "Campione", slug: "campione" },
  { name: "Canaan", slug: "canaan" },
  { name: "Claymore", slug: "claymore" },
  { name: "CodeBreaker", slug: "code-breaker" },
  { name: "CorpseParty", slug: "corpse-party" },
  { name: "Orb", slug: "orb-on-the-movements-of-the-earth" },
  {
    name: "TheWeakestTamerBeganAJourneyToPickUpTrash",
    slug: "the-weakest-tamer-began-a-journey-to-pick-up-trash",
  },
  { name: "Tsukimichi", slug: "tsukimichi-moonlit-fantasy" },
  { name: "UnnamedMemory", slug: "unnamed-memory" },
  {
    name: "TheWrongWayToUseHealingMagic",
    slug: "the-wrong-way-to-use-healing-magic",
  },
  { name: "VillainessLevel99", slug: "villainess-level-99" },
  { name: "HokkaidoGals", slug: "hokkaido-gals-are-super-adorable" },
  { name: "PsychoPass", slug: "psycho-pass" },
  { name: "LeGarconDaCote", slug: "le-garcon-da-cote" },
  { name: "MonVoisinTotoro", slug: "mon-voisin-totoro" },
  { name: "GamblingSchool", slug: "gambling-school" },
  { name: "BeyondTheBoundary", slug: "beyond-the-boundary" },
  { name: "GuiltyCrown", slug: "guilty-crown" },
  { name: "AkatsukiNoYona", slug: "akatsuki-no-yona" },
  { name: "Overlord", slug: "overlord" },
  { name: "Horimiya", slug: "horimiya" },
  { name: "Darling", slug: "darling-in-the-franxx" },
  { name: "Orange", slug: "orange" },
  { name: "LesEnfantsLoups", slug: "les-enfants-loups-ame-yuki" },
  { name: "Free", slug: "free" },
  {
    name: "ElfBride",
    slug: "an-archdemons-dilemma-how-to-love-your-elf-bride",
  },
  { name: "TheAncientMagusBride", slug: "the-ancient-magus-bride" },
  { name: "DeadmanWonderland", slug: "deadman-wonderland" },
  { name: "TerrorInResonance", slug: "terror-in-resonance" },
  { name: "GoldenTime", slug: "golden-time" },
  { name: "MFGhost", slug: "mf-ghost" },
  {
    name: "Prince7th",
    slug: "i-was-reincarnated-as-the-7th-prince-so-i-can-take-my-time-perfecting-my-magical-ability",
  },
  { name: "UruseiYatsura", slug: "urusei-yatsura" },
  { name: "Lookism", slug: "lookism" },
  { name: "ShamanKing", slug: "shaman-king" },
  { name: "LaLegendeDeKorra", slug: "la-legende-de-korra" },
  { name: "LesMursVagabonds", slug: "les-murs-vagabonds" },
  { name: "Hinamizawa", slug: "hinamizawa-le-village-maudit" },
  {
    name: "TheStrongestSageWithTheWeakestCrest",
    slug: "the-strongest-sage-with-the-weakest-crest",
  },
  { name: "AkudamaDrive", slug: "akudama-drive" },
  {
    name: "SekaiSaikouNoAssassin",
    slug: "the-worlds-finest-assassin-gets-reincarnated-in-another-world-as-an-aristocrat",
  },
  {
    name: "CriminellesFiancailles",
    slug: "yakuza-fiance-raise-wa-tanin-ga-ii",
  },
  {
    name: "TheReturnOfTheDisasterClassHero",
    slug: "the-return-of-the-disaster-class-hero",
  },
  { name: "MakeHeroineGaOosugiru", slug: "make-heroine-ga-ooisugiru" },
  { name: "Arcane", slug: "arcane" },
  { name: "AhiruNoSora", slug: "ahiru-no-sora" },
  { name: "LookBack", slug: "look-back" },
  { name: "AshitaNoJoe", slug: "ashita-no-joe" },
  { name: "Euphonium", slug: "hibike-euphonium" },
  { name: "MoDaoZuShi", slug: "mo-dao-zu-shi" },
  {
    name: "TheMostNotoriousTalker",
    slug: "the-most-notorious-talker-runs-the-worlds-greatest-clan",
  },
  {
    name: "AsAReincarnatedAristocratIllUseMyAppraisalSkillToRiseInTheNewWorld",
    slug: "as-a-reincarnated-aristocrat-ill-use-my-appraisal-skill-to-rise-in-the-world",
  },
  { name: "GoodByeDragonLife", slug: "goodbye-dragon-life" },
  {
    name: "TheUnwantedUndeadAdventurer",
    slug: "the-unwanted-undead-adventurer",
  },
  { name: "BananaFish", slug: "banana-fish" },
  { name: "Nagatoro", slug: "arrete-de-me-harceler-nagatoro" },
  { name: "UQHolder", slug: "uq-holder" },
  { name: "ScissorSeven", slug: "scissor-seven" },
  { name: "GijiHarem", slug: "giji-harem" },
  { name: "TrueBeauty", slug: "true-beauty" },
  { name: "Drifters", slug: "drifters" },
  { name: "FogHillOfFiveElements", slug: "fog-hill-of-the-five-elements" },
  { name: "KabaneriOfTheIconFortress", slug: "kabaneri-of-the-iron-fortress" },
  { name: "TonikakuKawai", slug: "tonikawa-over-the-moon-for-you" },
  { name: "MyMasterHasNoTail", slug: "my-master-has-no-tail" },
  { name: "Toriko", slug: "toriko" },
  { name: "Dumbbell", slug: "dumbbell-combien-tu-peux-soulever" },
  { name: "KemonoJihen", slug: "kemono-jihen" },
  { name: "AngeDaCote", slug: "chouchoute-par-lange-da-cote" },
  { name: "FourCutHero", slug: "4-cut-hero" },
  {
    name: "TheDemonSwordMasterOfExcaliburAcademy",
    slug: "the-demon-sword-master-of-excalibur-academy",
  },
  {
    name: "CheatSkillLevelUp",
    slug: "i-got-a-cheat-skill-in-another-world-and-became-unrivaled-in-the-real-world-too",
  },
  { name: "CallOfTheNight", slug: "call-of-the-night" },
  { name: "DaysToTheWedding", slug: "365-days-to-the-wedding" },
  { name: "Danganronpa", slug: "danganronpa" },
  { name: "SchoolDays", slug: "school-days" },
  {
    name: "AkashicRecords",
    slug: "akashic-records-of-bastard-magic-instructor",
  },
  { name: "MechaUde", slug: "mecha-ude" },
  { name: "IWantToEatYourPancreas", slug: "je-veux-manger-ton-pancreas" },
  { name: "LaVoieDuTablier", slug: "la-voie-du-tablier" },
  { name: "Radiant", slug: "radiant" },
  { name: "KuboWontLetMeBeInvisible", slug: "kubo-wont-let-me-be-invisible" },
  { name: "UzakiHana", slug: "uzaki-chan-wa-asobitai" },
  { name: "HitoriNoShita", slug: "hitori-no-shita-the-outcast" },
  { name: "DGrayMan", slug: "d-gray-man" },
  { name: "NegativePositiveAngler", slug: "negative-positive-angler" },
  { name: "HighCard", slug: "high-card" },
  { name: "SagaOfTanyaTheEvil", slug: "saga-of-tanya-the-evil" },
  { name: "SengokuYouko", slug: "sengoku-youko" },
  {
    name: "SummonedToAnotherWorldForASecondTime",
    slug: "je-me-fais-isekai-pour-la-deuxieme-fois-ca-commence-a-faire-beaucoup",
  },
  { name: "ToiletBoundHanakoKun", slug: "toilet-bound-hanako-kun" },
  {
    name: "TheReincarnationOfTheStrongestExorcistInAnotherWorld",
    slug: "the-reincarnation-of-the-strongest-exorcist-in-another-world",
  },
  { name: "Chihayafuru", slug: "chihayafuru" },
  { name: "DarwinsGame", slug: "darwins-game" },
  {
    name: "AngelIncluded",
    slug: "studio-apartment-good-lighting-angel-included",
  },
  { name: "Dororo", slug: "dororo" },
  { name: "AtelierDesSorciers", slug: "latelier-des-sorciers" },
  {
    name: "TheFragrantFlowerBloomsWithDignity",
    slug: "the-fragrant-flower-blooms-with-dignity",
  },
  { name: "WitchCraftWorks", slug: "witch-craft-works" },
  { name: "LeGarconEtLeHeron", slug: "le-garcon-et-le-heron" },
  {
    name: "TrappedInADatingSim",
    slug: "trapped-in-a-dating-sim-the-world-of-otome-games-is-tough-for-mobs",
  },
  {
    name: "ArriettyLePetitMondeDesChapardeurs",
    slug: "arrietty-le-petit-monde-des-chapardeurs",
  },
  { name: "Lv999", slug: "loving-yamada-at-lv999" },
  { name: "SkyHighSurvival", slug: "sky-high-survival" },
  { name: "YuriOnIce", slug: "yuri-on-ice" },
  { name: "TheKingsAvatar", slug: "the-kings-avatar" },
  { name: "RickEtMorty", slug: "rick-et-morty" },
  {
    name: "OurDatingStory",
    slug: "our-dating-story-the-experienced-you-and-the-inexperienced-me",
  },
  { name: "MasamuneRevenge", slug: "masamune-kuns-revenge" },
  { name: "AnotherJourneyToTheWest", slug: "another-journey-to-the-west" },
  { name: "AConditionCalledLove", slug: "a-condition-called-love" },
  { name: "LoveAndLies", slug: "love-and-lies" },
  { name: "ThePrinceOfTennis", slug: "the-prince-of-tennis-ii" },
  {
    name: "TheTunnelToSummer",
    slug: "the-tunnel-to-summer-the-exit-of-goodbye",
  },
  { name: "Shikimori", slug: "shikimori-nest-pas-juste-mignonne" },
  { name: "MermaidMelody", slug: "mermaid-melody-pichi-pichi-pitch" },
  { name: "SpiderSoWhat", slug: "so-im-a-spider-so-what" },
  { name: "PlatinumEnd", slug: "platinum-end" },
  {
    name: "AttaqueDesTitansJunior",
    slug: "lattaque-des-titans-junior-high-school",
  },
  { name: "TomozakiKun", slug: "the-low-tier-character-tomozaki-kun" },
  { name: "BlueWolves", slug: "blue-wolves" },
  { name: "TheBeginning", slug: "b-the-beginning" },
  { name: "Caligula", slug: "caligula" },
  { name: "WonderEggPriority", slug: "wonder-egg-priority" },
  {
    name: "YamadaKunAndTheSevenWitches",
    slug: "yamada-kun-and-the-seven-witches",
  },
  { name: "ASignOfAffection", slug: "a-sign-of-affection" },
  {
    name: "InAnotherWorldWithMySmartphone",
    slug: "in-another-world-with-my-smartphone",
  },
  { name: "NinaTheStarryBride", slug: "nina-du-royaume-aux-etoiles" },
  {
    name: "ImTheVilainessSoImTamingTheFinalBoss",
    slug: "im-the-villainess-so-im-taming-the-final-boss",
  },
  {
    name: "Level2CheatPowers",
    slug: "chillin-in-another-world-with-level-2-super-cheat-powers",
  },
  {
    name: "KurasuNoDaikirai",
    slug: "im-getting-married-to-a-girl-i-hate-in-my-class",
  },
  { name: "YozakuraFamily", slug: "mission-yozakura-family" },
  {
    name: "Girlfriends100",
    slug: "the-100-girlfriends-who-really-really-really-really-really-love-you",
  },
  {
    name: "TheQuintessentialQuintuplets",
    slug: "the-quintessential-quintuplets",
  },
  { name: "GimaiSeikatsu", slug: "gimai-seikatsu" },
  { name: "TrinitySeven", slug: "trinity-seven" },
  { name: "BeastTamer", slug: "beast-tamer" },
  {
    name: "Slimes300Years",
    slug: "ive-been-killing-slimes-for-300-years-and-maxed-out-my-level",
  },
  { name: "PrincessConnectReDive", slug: "princess-connect-re-dive" },
  { name: "TheHiddenDungeon", slug: "the-hidden-dungeon-only-i-can-enter" },
  {
    name: "GreatestAlchemist",
    slug: "possibly-the-greatest-alchemist-of-all-time",
  },
  { name: "Kimisen", slug: "our-last-crusade-or-the-rise-of-a-new-world" },
  { name: "Amagami", slug: "tying-the-knot-with-an-amagami-sister" },
  { name: "RentAGirlfriend", slug: "rent-a-girlfriend" },
  { name: "ToYourEternity", slug: "to-your-eternity" },
  { name: "KuroiwaMedaka", slug: "craque-pour-moi-medaka" },
  { name: "BattleGame", slug: "battle-game-in-5-seconds" },
  { name: "MyriadColorsPhantomWorld", slug: "myriad-colors-phantom-world" },
  { name: "CupidsChocolate", slug: "cupids-chocolate" },
  {
    name: "VermeilInGold",
    slug: "vermeil-in-gold-a-desperate-magician-barges-into-the-magical-world-alongside-the-strongest-calamity",
  },
  { name: "Wakfu", slug: "wakfu" },
  { name: "ShugoChara", slug: "shugo-chara" },
  { name: "Nana", slug: "nana" },
  { name: "PrincesseSarah", slug: "princesse-sarah" },
  {
    name: "Shimoneta",
    slug: "shimoneta-a-boring-world-where-the-concept-of-dirty-jokes-doesnt-exist",
  },
  { name: "TheNewGate", slug: "the-new-gate" },
  { name: "WanderingWitch", slug: "wandering-witch-the-journey-of-elaina" },
  {
    name: "EvenGivenTheWorthless",
    slug: "even-given-the-worthless-appraiser-class-im-actually-the-strongest",
  },
  { name: "DomesticGirlfriend", slug: "domestic-girlfriend" },
  { name: "DiabolicLovers", slug: "diabolik-lovers" },
  {
    name: "ILeftMyARankParty",
    slug: "i-left-my-a-rank-party-to-help-my-former-students-reach-the-dungeon-depths",
  },
  { name: "SayILoveYou", slug: "say-i-love-you" },
  { name: "OuranHighSchool", slug: "ouran-high-school-host-club" },
  { name: "IHaveACrushAtWork", slug: "i-have-a-crush-at-work" },
  { name: "TheDreamingBoyIsARealist", slug: "the-dreaming-boy-is-a-realist" },
  {
    name: "Okitsura",
    slug: "okitsura-fell-in-love-with-an-okinawan-girl-but-i-just-wish-i-know-what-shes-saying",
  },
  { name: "Ryman", slug: "rymans-club" },
  { name: "TheGirlDownstairs", slug: "the-girl-downstairs" },
  { name: "RomanticKiller", slug: "romantic-killer" },
  {
    name: "MyInstantDeathAbilityIsSoOverpowered",
    slug: "my-instant-death-ability-is-so-overpowered-no-one-in-this-other-world-stands-a-chance-against-me",
  },
  { name: "Beastars", slug: "beastars" },
  { name: "LinkClick", slug: "link-click" },
  { name: "BloodOfZeus", slug: "blood-of-zeus" },
  { name: "Overtake", slug: "overtake" },
  { name: "CleanFreak", slug: "clean-freak-aoyama-kun" },
  { name: "TheGeneOfAI", slug: "the-gene-of-ai" },
  { name: "ProtocolRain", slug: "protocol-rain" },
  { name: "TomogareOutFocus", slug: "twilight-out-of-focus" },
  { name: "Zom100", slug: "zom-100-bucket-list-of-the-dead" },
  { name: "Gachiakuta", slug: "gachiakuta" },
  { name: "DeathMarch", slug: "death-march-to-the-parallel-world-rhapsody" },
  { name: "DimensionalSeduction", slug: "2-5-dimensional-seduction" },
  {
    name: "BerserkOfGlutonny",
    slug: "berserk-of-gluttony-the-one-that-exceeds-the-concept-of-levels",
  },
  { name: "UncleFromAnotherWorld", slug: "coma-heroique-dans-un-autre-monde" },
  { name: "MyStepmomDaughterIsMyEx", slug: "my-stepmoms-daughter-is-my-ex" },
  {
    name: "TheIrregularAtMagicHighSchool",
    slug: "the-irregular-at-magic-high-school",
  },
  {
    name: "Beheneko",
    slug: "beheneko-the-elf-girls-cat-is-secretly-an-s-ranked-monster",
  },
  { name: "Bucchigire", slug: "shine-on-bakumatsu-boys" },
  {
    name: "TheGreatestDemonLord",
    slug: "the-greatest-demon-lord-is-reborn-as-a-typical-nobody",
  },
  { name: "TwinStarExorcist", slug: "twin-star-exorcists" },
  { name: "DragonRaja", slug: "dragon-raja-the-blazing-dawn" },
  {
    name: "FailureSkillNutMaster",
    slug: "bogus-skill-fruitmaster-about-that-time-i-became-able-to-eat-unlimited-numbers-of-skill-fruits-that-kill-you",
  },
  { name: "TabooTattoo", slug: "taboo-tattoo" },
  { name: "QuandTakagiMeTaquine", slug: "quand-takagi-me-taquine" },
  {
    name: "ToTheAbandonedSacredBeasts",
    slug: "to-the-abandoned-sacred-beasts",
  },
  { name: "RevengeOfTheIronBlooded", slug: "return-of-the-iron-blooded-hound" },
  { name: "FLCL", slug: "flcl" },
  { name: "YokaiWatch", slug: "yo-kai-watch" },
  { name: "DemonSlave", slug: "demon-slave" },
  { name: "Shy", slug: "shy" },
  { name: "Hanebad", slug: "hanebado" },
  { name: "KanataNoAstra", slug: "astra-lost-in-space" },
  { name: "ACertainMagicalIndex", slug: "a-certain-magical-index" },
  { name: "PuellaMagica", slug: "puella-magi-madoka-magica" },
  {
    name: "PuellaMagicaGaiden",
    slug: "magia-record-puella-magi-madoka-magica-side-story",
  },
  { name: "LoveIsHardForOtaku", slug: "wotakoi-love-is-hard-for-otaku" },
  { name: "SugarAppleFairyTale", slug: "sugar-apple-fairy-tale" },
  { name: "HeavenOfficial", slug: "heaven-officials-blessing" },
  { name: "LaPrincesseEtLaBete", slug: "la-princesse-et-la-bete" },
  { name: "VampireDormitory", slug: "vampire-dormitory" },
  {
    name: "TheRedRanger",
    slug: "the-red-ranger-becomes-an-adventurer-in-another-world",
  },
  { name: "TheSaintsMagicPower", slug: "the-saints-magic-power-is-omnipotent" },
  {
    name: "RebornToMasterTheBlade",
    slug: "reborn-to-master-the-blade-from-hero-king-to-extraordinary-squire",
  },
  { name: "Amnesia", slug: "amnesia" },
  { name: "MyDeerFriendNokotan", slug: "my-deer-friend-nokotan" },
  { name: "KissHimNotMe", slug: "kiss-him-not-me" },
  { name: "Ishura", slug: "ishura" },
  { name: "APlayThrough", slug: "a-playthrough-of-a-certain-dudes-vrmmo-life" },
  { name: "HoneyLemonSoda", slug: "honey-lemon-soda" },
  { name: "WelcomeToJapan", slug: "welcome-to-japan-ms-elf" },
  { name: "WelcomeToDemonSchool", slug: "welcome-to-demon-school-iruma-kun" },
  {
    name: "MyUniqueSkill",
    slug: "my-unique-skill-makes-me-op-even-at-level-1",
  },
  { name: "Raeliana", slug: "comment-raeliana-a-survecu-au-manoir-wynknight" },
  { name: "SasakiAndMiyano", slug: "sasaki-and-miyano" },
  { name: "AiyouDeMishi", slug: "x-y" },
  { name: "DeadMountDeathPlay", slug: "dead-mount-death-play" },
  {
    name: "CherryMagic",
    slug: "cherry-magic-thirty-years-of-virginity-can-make-you-a-wizard",
  },
  { name: "GoldenBoy", slug: "golden-boy" },
  { name: "IsekaiCheatMagician", slug: "isekai-cheat-magician" },
  { name: "UbelBlatt", slug: "ubel-blatt" },
  { name: "SK8TheInfinity", slug: "sk8-the-infinity" },
  { name: "TheFarawayPaladin", slug: "the-faraway-paladin" },
  { name: "HowNotToSummonADemonLord", slug: "how-not-to-summon-a-demon-lord" },
  {
    name: "ImANoble",
    slug: "im-a-noble-on-the-brink-of-ruin-so-i-might-as-well-try-mastering-magic",
  },
  { name: "AstroRoyale", slug: "astro-royale" },
  {
    name: "JeSuisUnAssassin",
    slug: "je-suis-un-assassin-et-je-surpasse-le-heros",
  },
  {
    name: "TheBanishedFormerHero",
    slug: "the-banished-former-hero-lives-as-he-pleases",
  },
  { name: "LesCombattants", slug: "les-combattants-seront-deployes" },
  { name: "Existence", slug: "existence" },
  { name: "Mieruko", slug: "mieruko-chan" },
  { name: "Zenshu", slug: "zenshu" },
  { name: "WhisperMeALoveSong", slug: "whisper-me-a-love-song" },
  { name: "Dynazenon", slug: "ssss-dynazenon" },
  { name: "Gridman", slug: "ssss-gridman" },
  {
    name: "Cambrousard",
    slug: "suppose-a-kid-from-the-last-dungeon-boonies-moved-to-a-starter-town",
  },
  { name: "LeftHandLayup", slug: "left-hand-layup" },
  { name: "ClassroomForHeroes", slug: "classroom-for-heroes" },
  { name: "NoLongerRangers", slug: "go-go-loser-ranger" },
  { name: "Ordeal", slug: "ordeal" },
  { name: "TomoChan", slug: "tomo-chan-est-une-fille" },
  { name: "Questism", slug: "questism" },
  { name: "ShironekoProject", slug: "shironeko-project-zero-chronicle" },
  { name: "DevilsLine", slug: "devils-line" },
  { name: "Komi", slug: "komi-cherche-ses-mots" },
  { name: "TengokuDaimakyou", slug: "heavenly-delusion" },
  { name: "Kiznaiver", slug: "kiznaiver" },
  { name: "TheDevilIsAPartTimer", slug: "the-devil-is-a-part-timer" },
  { name: "Gokurakugai", slug: "gokurakugai" },
  { name: "TheKingdomsOfRuin", slug: "the-kingdoms-of-ruin" },
  { name: "Plunderer", slug: "plunderer" },
  { name: "Ajin", slug: "ajin" },
  { name: "AceOfDiamond", slug: "ace-of-diamond" },
  { name: "RunWithTheWind", slug: "run-with-the-wind" },
  { name: "Shirobako", slug: "shirobako" },
  { name: "KillLaKill", slug: "kill-la-kill" },
  { name: "SpaceDandy", slug: "space-dandy" },
  { name: "PingPong", slug: "ping-pong-the-animation" },
  { name: "LereDesCristaux", slug: "lere-des-cristaux" },
  { name: "TheDoOver", slug: "the-do-over-damsel-conquers-the-dragon-emperor" },
  {
    name: "ISomehow",
    slug: "ive-somehow-gotten-stronger-when-i-improved-my-farm-related-skills",
  },
  { name: "Alderamin", slug: "alderamin-on-the-sky" },
  { name: "Hundred", slug: "hundred" },
  {
    name: "CautiousHero",
    slug: "cautious-hero-the-hero-is-overpowered-but-overly-cautious",
  },
  { name: "AReturner", slug: "a-returners-magic-should-be-special" },
  { name: "GranblueFantasy", slug: "granblue-fantasy-the-animation" },
  { name: "RealistHero", slug: "how-a-realist-hero-rebuilt-the-kingdom" },
  {
    name: "DisgracedNoble",
    slug: "im-giving-the-disgraced-noble-lady-i-rescued-a-crash-course-in-naughtiness",
  },
  { name: "ForgotHerGlasses", slug: "the-girl-i-like-forgot-her-glasses" },
  { name: "GoodnightPunpun", slug: "bonne-nuit-punpun" },
  { name: "MyOneHitKillSister", slug: "my-one-hit-kill-sister" },
  { name: "Pokemon", slug: "pokemon" },
  { name: "ParryEverything", slug: "i-parry-everything" },
  { name: "MegaloBox", slug: "megalo-box" },
  { name: "BurnTheWitch", slug: "burn-the-witch" },
  { name: "KotaroEnSolo", slug: "kotaro-en-solo" },
  { name: "MortImminente", slug: "mort-imminente" },
  { name: "DarkerThanBlack", slug: "darker-than-black" },
  {
    name: "GuildReceptionist",
    slug: "i-may-be-a-guild-receptionist-but-ill-solo-any-boss-to-clock-out-on-time",
  },
  { name: "LeVentSeLeve", slug: "le-vent-se-leve" },
  { name: "LittleWitchAcademia", slug: "little-witch-academia" },
  { name: "JuuniTaisen", slug: "juni-taisen-zodiac-war" },
  { name: "Rokka", slug: "rokka-braves-of-the-six-flowers" },
  { name: "MsServant", slug: "you-are-ms-servant" },
  { name: "TearmoonEmpire", slug: "tearmoon-empire" },
  { name: "CaroleAndTuesday", slug: "carole-tuesday" },
  { name: "WelcomeToTheBallroom", slug: "welcome-to-the-ballroom" },
  { name: "SuperCube", slug: "super-cube" },
  { name: "TalesOfTheWeddingRings", slug: "tales-of-wedding-rings" },
  {
    name: "TheDailyLifeOfAMiddleAged",
    slug: "the-daily-life-of-a-middle-aged-online-shopper-in-another-world",
  },
  { name: "ManagerKim", slug: "manager-kim" },
  { name: "JoursAvantTaMort", slug: "100-jours-avant-ta-mort" },
  { name: "BlueGiant", slug: "blue-giant" },
  { name: "BlackBullet", slug: "black-bullet" },
  { name: "Kobayashi", slug: "miss-kobayashis-dragon-maid-s" },
  { name: "Iroduku", slug: "iroduku-le-monde-en-couleur" },
  { name: "AoChan", slug: "ao-chan-cant-study" },
  { name: "NonNonBiyori", slug: "non-non-biyori" },
  { name: "Invincible", slug: "invincible" },
  { name: "Goldorak", slug: "goldorak" },
  { name: "Hitorijime", slug: "hitorijime-my-hero" },
  { name: "TheBeginningAfterTheEnd", slug: "the-beginning-after-the-end" },
  {
    name: "TheMostHereticalLastBossQueen",
    slug: "the-most-heretical-last-boss-queen-from-villainess-to-savior",
  },
  { name: "LesEnfantsDuTemps", slug: "les-enfants-du-temps" },
  { name: "Index", slug: "magi-adventure-of-sinbad" },
  {
    name: "Chillin",
    slug: "chillin-in-my-30s-after-getting-fired-from-the-demon-kings-army",
  },
  { name: "AscendanceOfABookworm", slug: "ascendance-of-a-bookworm" },
  { name: "TheDungeonOfBlackCompany", slug: "the-dungeon-of-black-company" },
  { name: "Noblesse", slug: "noblesse" },
  { name: "ParanoiaAgent", slug: "paranoia-agent" },
  { name: "BlackSummoner", slug: "black-summoner" },
  { name: "UnbreakableMachineDoll", slug: "unbreakable-machine-doll" },
  { name: "BloodBlockade", slug: "blood-blockade-battlefront" },
  { name: "PeachBoyRiverside", slug: "peach-boy-riverside" },
  { name: "Yuzuki", slug: "les-quatre-freres-yuzuki" },
  { name: "Gumball", slug: "le-monde-incroyable-de-gumball" },
  {
    name: "BrillantHealer",
    slug: "the-brilliant-healers-new-life-in-the-shadows",
  },
  {
    name: "FromOldCountry",
    slug: "from-old-country-bumpkin-to-master-swordsman",
  },
  { name: "PrincesseKaguya", slug: "le-conte-de-la-princesse-kaguya" },
  { name: "MesVoisinsLesYamada", slug: "mes-voisins-les-yamada" },
  { name: "ToBeHero", slug: "to-be-hero" },
  { name: "ToBeHeroine", slug: "to-be-heroine" },
  { name: "ToBeHeroX", slug: "to-be-hero-x" },
  { name: "DevilMayCry", slug: "devil-may-cry" },
  { name: "SiTuTendsLoreille", slug: "si-tu-tends-loreille" },
  { name: "ZatsuTabi", slug: "zatsutabi-thats-journey" },
  { name: "SummerPockets", slug: "summer-pockets" },
  { name: "ReMain", slug: "re-main" },
  { name: "Days", slug: "days" },
  {
    name: "SwordOfTheDemonHunter",
    slug: "sword-of-the-demon-hunter-kijin-gentosho",
  },
  { name: "Lazarus", slug: "lazarus" },
  { name: "TigreEtPoissons", slug: "josee-le-tigre-et-les-poissons" },
  { name: "AmIActuallyTheStrongest", slug: "am-i-actually-the-strongest" },
  { name: "AharenSan", slug: "aharen-san-wa-hakarenai" },
  {
    name: "Mononoke",
    slug: "the-mononoke-lecture-logs-of-chuzenji-sensei-he-just-solves-all-the-mysteries",
  },
  { name: "TheShiunjiFamily", slug: "the-shiunji-family-children" },
  { name: "OnceUponAWitchDeath", slug: "once-upon-a-witchs-death" },
  { name: "CatchMeAtTheBallpark", slug: "catch-me-at-the-ballpark" },
  { name: "ApocalypseHotel", slug: "apocalypse-hotel" },
  { name: "YourForma", slug: "your-forma" },
  {
    name: "TheTooPerfectSaint",
    slug: "the-too-perfect-saint-tossed-aside-by-my-fiance-and-sold-to-another-kingdom",
  },
  { name: "Moonrise", slug: "moonrise" },
  { name: "Ninkoro", slug: "a-ninja-and-an-assassin-under-one-roof" },
  { name: "Teogonia", slug: "teogonia" },
  { name: "Yaiba", slug: "yaiba-samurai-legend" },
  { name: "RockIsALady", slug: "rock-is-a-ladys-modesty" },
  { name: "CanABoyGirl", slug: "can-a-boy-girl-friendship-survive" },
  { name: "ByeByeEarth", slug: "bye-bye-earth" },
  { name: "TheDinnerTableDetective", slug: "the-dinner-table-detective" },
  { name: "WitchWatch", slug: "witch-watch" },
  { name: "AnneShirley", slug: "anne-shirley" },
  { name: "KowloonGenericRomance", slug: "kowloon-generic-romance" },
  { name: "Mono", slug: "mono" },
  { name: "FoodForTheSoul", slug: "food-for-the-soul" },
  { name: "ShoushiminSeries", slug: "shoshimin-how-to-become-ordinary" },
  { name: "TheGorillaGod", slug: "the-gorilla-gods-go-to-girl" },
  { name: "TheUnawareAtelierMaster", slug: "the-unaware-atelier-meister" },
  { name: "RonKamonohashi", slug: "ron-kamonohashis-forbidden-deductions" },
  {
    name: "RebornAsAVendingMachine",
    slug: "reborn-as-a-vending-machine-i-now-wander-the-dungeon",
  },
  { name: "LycorisRecoil", slug: "lycoris-recoil" },
  { name: "Umamusume", slug: "umamusume-pretty-derby" },
  { name: "DeliciousInDungeon", slug: "delicious-in-dungeon" },
  { name: "WiseMansGrandchild", slug: "wise-mans-grandchild" },
  { name: "LoveOfKill", slug: "love-of-kill" },
  { name: "Bones", slug: "bones" },
  { name: "Dorohedoro", slug: "dorohedoro" },
  { name: "HinataNoAoshigure", slug: "hinata-no-aoshigure" },
  { name: "PerfectBlue", slug: "perfect-blue" },
  { name: "RideYourWave", slug: "ride-your-wave" },
  {
    name: "ImTheEvilLord",
    slug: "im-the-evil-lord-of-an-intergalactic-empire",
  },
  { name: "StarsAlign", slug: "stars-align" },
  { name: "LogHorizon", slug: "log-horizon" },
  { name: "TokyoMagnitude", slug: "tokyo-magnitude-8-0" },
  { name: "Nichijou", slug: "nichijou-my-ordinary-life" },
  { name: "WorldTrigger", slug: "world-trigger" },
  { name: "BackStreetGirls", slug: "back-street-girls-gokudols" },
  { name: "BNA", slug: "bna-brand-new-animal" },
  { name: "FirePunch", slug: "fire-punch" },
  { name: "NHK", slug: "welcome-to-the-n-h-k" },
  { name: "TheTatamiGalaxy", slug: "the-tatami-galaxy" },
  { name: "TheWitchAndTheBeast", slug: "the-witch-and-the-beast" },
  { name: "KuzuNoHonkai", slug: "kuzu-no-honkai" },
  { name: "IShallSurvive", slug: "i-shall-survive-using-potions" },
  { name: "YoungGTO", slug: "young-gto" },
  { name: "ThePetGirlOfSakurasou", slug: "the-pet-girl-of-sakurasou" },
  { name: "Inuyashiki", slug: "inuyashiki-last-hero" },
  { name: "YowamushiPedal", slug: "yowamushi-pedal" },
  { name: "Bubble", slug: "bubble" },
  { name: "ShakuganNoShana", slug: "shakugan-no-shana" },
  {
    name: "VolleyballClub",
    slug: "2-43-seiin-high-school-boys-volleyball-team",
  },
  { name: "GrandpaAndGrandma", slug: "grandpa-and-grandma-turn-young-again" },
  { name: "CardCaptorSakura", slug: "cardcaptor-sakura" },
  { name: "TheOwlHouse", slug: "luz-a-osville" },
  { name: "Vigilantes", slug: "my-hero-academia-vigilantes" },
  {
    name: "MyNextLifeAsAVilainess",
    slug: "my-next-life-as-a-villainess-all-routes-lead-to-doom",
  },
  { name: "SakuraTrick", slug: "sakura-trick" },
  { name: "Nisekoi", slug: "nisekoi-false-love" },
  { name: "ShinobiNoIttoki", slug: "shinobi-no-ittoki" },
  { name: "SuiseiNoGargantia", slug: "gargantia-on-the-verdurous-planet" },
];

const fs = require("fs");

const dirs = fs.readdirSync("./Animes/");

animes.map(({ name, slug }) => {
  const dir = dirs.find((d) => d.toLowerCase() === name.toLowerCase());

  if (dir) {
    fs.renameSync(`./Animes/${dir}`, `./Animes/${slug}`);
  } else {
    console.log("PAS TROUVE POUR ", name);
  }
});
